apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data
  namespace: monitoring-stack
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring-stack
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      nodePort: 30093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.26.0
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.external-url=http://localhost:30093
          ports:
            - containerPort: 9093
              name: http
          volumeMounts:
            - name: cfg
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
            - name: data
              mountPath: /alertmanager
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
      volumes:
        - name: cfg
          configMap:
            name: alertmanager-config
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-data
